server.port=8080

spring.application.name=ojas-backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ojas_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.naadi.ojas=DEBUG

# Show Spring Web request details
logging.level.org.springframework.web=DEBUG

# Show Spring Security logs
logging.level.org.springframework.security=DEBUG

# Show Mail / Gmail SMTP logs
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.jakarta.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# JavaMail SMTP debug
spring.mail.properties.mail.debug=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=naadidesigns.in@gmail.com
spring.mail.password=hswa llrp qtna lusn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000